FROM python:3.12-slim

RUN apt-get update && apt-get install -y curl git build-essential net-tools iproute2 libpq-dev

ENV PYTHONUNBUFFERED True

# set the working directory
WORKDIR /code

# install dependencies
COPY ./requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

# copy src code
COPY ./src ./src

ENV PYTHONPATH=/code/src

EXPOSE 8080

# start the server
CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8080", "--proxy-headers"]