FROM python:3.12-slim

RUN apt-get update && apt-get install -y curl git build-essential net-tools iproute2 libpq-dev

# set the working directory
WORKDIR /code

# install dependencies
COPY ./requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# copy the src to the folder
COPY .vscode/launch.json ./.vscode/launch.json
COPY ./src ./src

ENV PYTHONPATH=/code/src

# set up aliases
RUN echo "alias ga='git add'" >> ~/.bashrc \
  && echo "alias gaa='git add .'" >> ~/.bashrc \
  && echo "alias gaaa='git add --all'" >> ~/.bashrc \
  && echo "alias gau='git add --update'" >> ~/.bashrc \
  && echo "alias gb='git branch'" >> ~/.bashrc \
  && echo "alias gbd='git branch --delete'" >> ~/.bashrc \
  && echo "alias gc='git commit'" >> ~/.bashrc \
  && echo "alias gcm='git commit --message'" >> ~/.bashrc \
  && echo "alias gcf='git commit --fixup'" >> ~/.bashrc \
  && echo "alias gco='git checkout'" >> ~/.bashrc \
  && echo "alias gcob='git checkout -b'" >> ~/.bashrc \
  && echo "alias gcom='git checkout master'" >> ~/.bashrc \
  && echo "alias gcos='git checkout staging'" >> ~/.bashrc \
  && echo "alias gcod='git checkout develop'" >> ~/.bashrc \
  && echo "alias gd='git diff'" >> ~/.bashrc \
  && echo "alias gda='git diff HEAD'" >> ~/.bashrc \
  && echo "alias gi='git init'" >> ~/.bashrc \
  && echo "alias gl='git log'" >> ~/.bashrc \
  && echo "alias glg='git log --graph --oneline --decorate --all'" >> ~/.bashrc \
  && echo "alias gld='git log --pretty=format:\"%h %ad %s\" --date=short --all'" >> ~/.bashrc \
  && echo "alias gm='git merge --no-ff'" >> ~/.bashrc \
  && echo "alias gma='git merge --abort'" >> ~/.bashrc \
  && echo "alias gmc='git merge --continue'" >> ~/.bashrc \
  && echo "alias gp='git pull'" >> ~/.bashrc \
  && echo "alias gpr='git pull --rebase'" >> ~/.bashrc \
  && echo "alias gr='git rebase'" >> ~/.bashrc \
  && echo "alias gs='git status'" >> ~/.bashrc \
  && echo "alias gss='git status --short'" >> ~/.bashrc \
  && echo "alias gst='git stash'" >> ~/.bashrc \
  && echo "alias gsta='git stash apply'" >> ~/.bashrc \
  && echo "alias gstd='git stash drop'" >> ~/.bashrc \
  && echo "alias gstl='git stash list'" >> ~/.bashrc \
  && echo "alias gstp='git stash pop'" >> ~/.bashrc \
  && echo "alias gsts='git stash save'" >> ~/.bashrc